before_install:
  - export TOOLCHAIN_DIR=$PWD/toolchains 
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake wget bzip2

install:
  - ./configure.sh
  - export PATH=$PATH:$TOOLCHAIN_DIR/gcc-arm-none-eabi-4_9-2015q3/bin/

script: make

cache:
  apt: true

after_failure:
  - echo "TOOLCHAIN DIR =$$TOOLCHAIN_DIR"
  - echo "PATH          =$PATH"
  - ls -l $TOOLCHAIN_DIR/gcc-arm-none-eabi-4_9-2015q3/bin/

